# Generated by Django 3.1.3 on 2020-11-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('ssc_marks', models.IntegerField()),
                ('bie_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('father_name', models.TextField()),
                ('mother_name', models.TextField()),
                ('department', models.TextField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
